apiVersion: v1
kind: Service
metadata:
  name: canary-service
  labels:
    app: canary
    strimzi.io/kind: Canary
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  selector:
    matchLabels:
      app: canary
  replicas: 1
  template:
    metadata:
      labels:
        app: canary
        strimzi.io/kind: Canary
    spec:
      containers:
      - name: canary
        image: strimzi-canary:0.0.1
        ports:
        - containerPort: 8080
          name: rest-api
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap:9092"
 